# This is a basic workflow to help you get started with Actions

name: CI

on:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout The Code
        uses: actions/checkout@v2

      - name: upload html test report
        uses: actions/upload-artifact@v2
        with:
          name: lint.html
          path: app/build/reports/lint-results-debug.html


  unit-test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run tests
        run: ./gradlew test

      - name: upload html test report
        uses: actions/upload-artifact@v2
        with:
          name: unit-test-report
          path: app/build/reports/lint-results-debug.html


